# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d4d3d6048eed7e7798e9cd99989812cb02104cc85ccdce82d50450f90f183614b0700e28a8fb92296ba7fd74bb3d65c6b2442298ef83f3056ab9409a1b21b03

test:
  secret_key_base: a04278600b03631c0afba7a7345deb6b64e9c5299d5ae34f328dfa8cf66e14753b3a5a9a61a618eb9a3cc5f5b3832f81fe35394dac0351152f8b3f45dadeb5bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
